name: Delete Old Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行一次，避免过于频繁

jobs:
  del_runs:
    name: Delete old runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3          # 保留最近3天的记录
          keep_minimum_runs: 2    # 每个 workflow 至少保留2个运行实例
          # target_workflow_id: "your-workflow-filename.yml" # 可选：指定只清理某个特定的 workflow
